### ISSUE TITLE
Constant Change Detection Event Loop 

### ISSUE THREAD

**Issue by papastepano** [rainerhahnekamp/signals-unleashed#1]
Constant change detection events are occurring in the app, seemingly triggered by Keycloak in src/app/shared/security/security-store.ts, particularly from the loadedUser method in the header component.

**Steps to Reproduce:**

1. Start the application.
2. Observe the change detection events in the header component.
3. Expected Behavior: Change detection events should not be constantly triggered.

**Actual Behavior:**
Constant change detection events are being triggered, likely due to silent token checks by Keycloak.

**Investigation:**
Issue appears to stem from security-store.ts.
loadedUser method seems to trigger these events.
Suspected silent token checks by Keycloak.

**Proposed Discussion:**
Looking for more efficient ways to handle token checks or related processes to avoid constant change detection.

**Comment by rainerhahnekamp** [comment]
Hi @papastepano, pin-point root analysis. Thanks for that.

It is coming from the keycloak service, specifically `keycloak.init` needs to run outside zone.js. Do you want to create a PR?
