### ISSUE TITLE
Fix addFavourite() and removeFavorite() in `holidays-service.ts`

### ISSUE THREAD

**Issue by 0815Hunter** [rainerhahnekamp/signals-unleashed#2]
In your main branch, the functions
`addFavorite() `and `removeFavorite()` in `holidays-service.ts`
are not quite doing what they are supposed to, you might want to revisit them ;)

**Comment by rainerhahnekamp** [comment]
Hi @0815Hunter, thanks for noticing. Do you want to provide a PR?

**Comment by 0815Hunter** [comment]
Alright, why not
